//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfpEat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCategorie
    {
        public int IdMenu { get; set; }
        public int IdCategorie { get; set; }
        public int IdRestaurant { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
