//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfpEat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AfpEatEntities : DbContext
    {
        public AfpEatEntities()
            : base("name=AfpEatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<CommandeProduit> CommandeProduit { get; set; }
        public virtual DbSet<EtatCommande> EtatCommande { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<ProduitCategorie> ProduitCategorie { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SessionUtilisateur> SessionUtilisateur { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeCuisine> TypeCuisine { get; set; }
        public virtual DbSet<TypeVersement> TypeVersement { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
